"""
flask_caching._view_caching
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The :meth:`~flask_caching.Cache.cached` decorator and its supporting
:class:`_ViewCachingMixin`.

:copyright: (c) 2010 by Thadeus Burgess.
:license: BSD, see LICENSE for more details.
"""

import functools
import inspect
import logging
from collections.abc import Callable
from collections.abc import Iterable
from typing import Any
from typing import cast

from flask import g
from flask import request
from flask import Response
from flask import url_for
from werkzeug.exceptions import HTTPException

from ._typing import _AnyCachedFunction
from ._typing import _CachedFunction
from ._typing import P
from ._typing import R
from .core import _CacheCore
from .responses import CachedResponse
from .signals import cache_view_hit as cache_view_hit
from .signals import cache_view_miss as cache_view_miss
from .utils import _QueryArgs
from .utils import _Timeout
from .utils import get_arg_names
from .utils import join_generator
from .utils import normalize_timeout
from .utils import query_args_as_pairs

logger = logging.getLogger(__name__)


class _ViewCachingMixin(_CacheCore):
    """Adds :meth:`cached` view caching to :class:`~flask_caching.Cache`."""

    def cached(
        self,
        timeout: _Timeout | None = None,
        key_prefix: str | Callable[[], str] = "view/%s",
        unless: Callable[..., Any] | None = None,
        forced_update: Callable[..., Any] | None = None,
        is_stale: Callable[..., Any] | None = None,
        response_filter: Callable[..., Any] | None = None,
        query_string: bool = False,
        hash_method: Callable[..., Any] | None = None,
        cache_none: bool = False,
        make_cache_key: Callable[..., Any] | None = None,
        source_check: bool | None = None,
        response_hit_indication: bool | None = False,
    ) -> Callable[[Callable[P, R]], _CachedFunction[P, R]]:
        """Decorator. Use this to cache a function. By default the cache key
        is `view/request.path`. You are able to use this decorator with any
        function by changing the `key_prefix`. If the token `%s` is located
        within the `key_prefix` then it will replace that with `request.path`

        Example::

            # An example view function
            @cache.cached(timeout=50)
            def big_foo():
                return big_bar_calc()

            # An example misc function to cache.
            @cache.cached(key_prefix='MyCachedList')
            def get_list():
                return [random.randrange(0, 1) for i in range(50000)]

            my_list = get_list()

        .. note::

            You MUST have a request context to actually called any functions
            that are cached.

        .. versionadded:: 0.4
            The returned decorated function now has three function attributes
            assigned to it. These attributes are readable/writable.

                **uncached**
                    The original undecorated function

                **cache_timeout**
                    The cache timeout value for this function. For a
                    custom value to take affect, this must be set before the
                    function is called.

                **make_cache_key**
                    A function used in generating the cache_key used.

                    readable and writable

                    Outside of a request context, pass ``path`` to build the
                    key for a given ``request.path`` and, for
                    ``query_string=True``, ``query_args`` to build the key for
                    a given query string::

                        key = view.make_cache_key(
                            path="/works", query_args="limit=15&mock=true"
                        )
                        cache.delete(key)

                    ``query_args`` accepts a query string, a mapping or an
                    iterable of ``(key, value)`` pairs. See
                    :meth:`delete_cached` for the shorthand.

        :param timeout: Default None. If set to an integer, will cache for that
                        amount of time. Unit of time is in seconds. A
                        ``datetime.timedelta`` is also accepted and is rounded
                        up to whole seconds.

        :param key_prefix: Default 'view/%(request.path)s'. Beginning key to .
                           use for the cache key. `request.path` will be the
                           actual request path, or in cases where the
                           `make_cache_key`-function is called from other
                           views it will be the expected URL for the view
                           as generated by Flask's `url_for()`.

                           .. versionadded:: 0.3.4
                               Can optionally be a callable which takes
                               no arguments but returns a string that will
                               be used as the cache_key.

        :param unless: Default None. Cache will *always* execute the caching
                       facilities unless this callable is true.
                       This will bypass the caching entirely.

        :param forced_update: Default None. If this callable is true,
                              cache value will be updated regardless cache
                              is expired or not. Useful for background
                              renewal of cached functions.

        :param is_stale: Default None. Called on a cache hit with the cached
                         value as its first argument. If it is true the cached
                         value will be recomputed. If the callable accepts more
                         than one argument, the calls own arguments are passed
                         after the cached value.

        :param response_filter: Default None. If not None, the callable is
                                invoked after the cached function evaluation,
                                and is given one argument, the response
                                content. If the callable returns False, the
                                content will not be cached. Useful to prevent
                                caching of code 500 responses.

        :param query_string: Default False. When True, the cache key
                             used will be the result of hashing the
                             ordered query string parameters. This
                             avoids creating different caches for
                             the same query just because the parameters
                             were passed in a different order. See
                             _make_cache_key_query_string() for more
                             details.

        .. versionchanged:: 2.5.0
            Include ``key_prefix`` when building query string cache keys.

        :param hash_method: Default None. If None will use the value set by
                            ``CACHE_HASH_METHOD``, which defaults to
                            ``hashlib.sha256``. The hash method used to
                            generate the keys for cached results.
        :param cache_none: Default False. If set to True, add a key exists
                           check when cache.get returns None. This will likely
                           lead to wrongly returned None values in concurrent
                           situations and is not recommended to use.
        :param make_cache_key: Default None. If set to a callable object,
                           it will be called to generate the cache key

        :param source_check: Default None. If None will use the value set by
                             CACHE_SOURCE_CHECK.
                             If True, include the function's source code in the
                             hash to avoid using cached values when the source
                             code has changed and the input values remain the
                             same. This ensures that the cache_key will be
                             formed with the function's source code hash in
                             addition to other parameters that may be included
                             in the formation of the key.

        :param response_hit_indication: Default False.
                             If True, it will add to response header field 'hit_cache'
                             if used cache.

        .. versionchanged:: 2.5.0
            A ``werkzeug.exceptions.HTTPException`` raised by the decorated
            function, for example through Flask's ``abort()``, is now cached
            like a returned response and re-raised on a cache hit. Use
            ``response_filter``, which is given the exception's response, to
            keep it out of the cache.
        """

        def decorator(f: Callable[P, R]) -> _CachedFunction[P, R]:
            @functools.wraps(f)
            def decorated_function(*args: Any, **kwargs: Any) -> Any:
                #: Bypass the cache entirely.
                if self._bypass_cache(unless, f, *args, **kwargs):
                    return self._call_fn(f, *args, **kwargs)

                try:
                    if make_cache_key is not None and callable(make_cache_key):
                        cache_key = make_cache_key(*args, **kwargs)
                    else:
                        cache_key = cached_fn.make_cache_key(
                            *args, use_request=True, **kwargs
                        )

                    if self._forced_update(forced_update, *args, **kwargs):
                        rv = None
                        found = False
                    else:
                        rv = self.get(cache_key)
                        found = True

                        # If the value returned by cache.get() is None, it
                        # might be because the key is not found in the cache
                        # or because the cached value is actually None
                        if rv is None:
                            # If we're sure we don't need to cache None values
                            # (cache_none=False), don't bother checking for
                            # key existence, as it can lead to false positives
                            # if a concurrent call already cached the
                            # key between steps. This would cause us to
                            # return None when we shouldn't
                            if not cache_none:
                                found = False
                            else:
                                found = self.has(cache_key)

                        if found and self._is_stale(is_stale, rv, *args, **kwargs):
                            rv = None
                            found = False
                except Exception:
                    if self.app.debug:
                        raise
                    logger.exception("Exception possibly due to cache backend.")
                    return self._call_fn(f, *args, **kwargs)
                if found and self.app.debug:
                    logger.info(f"Cache used for key: {cache_key}")
                if response_hit_indication:
                    g.flask_caching_hit_cache = found

                    def apply_caching(response: Response) -> Response:
                        if g.get("flask_caching_hit_cache"):
                            response.headers["hit_cache"] = g.flask_caching_hit_cache
                        return response

                    after_request_funcs = self.app.after_request_funcs[None]
                    if not any(
                        getattr(func, "__name__", None) == "apply_caching"
                        for func in after_request_funcs
                    ):
                        after_request_funcs.append(apply_caching)

                if self.enable_signals:
                    signal = cache_view_hit if found else cache_view_miss
                    signal.send(
                        cache=self, cache_key=cache_key, args=args, kwargs=kwargs
                    )

                if found and isinstance(rv, HTTPException):
                    raise rv

                if not found:
                    rv = self._call_fn_or_exception(f, *args, **kwargs)
                    if inspect.isgenerator(rv):
                        rv = join_generator(rv)

                    if response_filter is None or response_filter(
                        rv.get_response() if isinstance(rv, HTTPException) else rv
                    ):
                        cache_timeout = normalize_timeout(cached_fn.cache_timeout)
                        if isinstance(rv, CachedResponse):
                            cache_timeout = rv.timeout or cache_timeout

                        try:
                            self.set(
                                cache_key,
                                rv,
                                timeout=cache_timeout,
                            )
                        except Exception:
                            if self.app.debug:
                                raise
                            logger.exception("Exception possibly due to cache backend.")

                    if isinstance(rv, HTTPException):
                        raise rv
                return rv

            def default_make_cache_key(*args: Any, **kwargs: Any) -> str:
                # Convert non-keyword arguments (which is the way
                # `make_cache_key` expects them) to keyword arguments
                # (the way `url_for` expects them)
                argspec_args = get_arg_names(f)

                for arg_name, arg in zip(argspec_args, args, strict=False):
                    kwargs[arg_name] = arg

                use_request = kwargs.pop("use_request", False)
                path = kwargs.pop("path", None)
                query_args = kwargs.pop("query_args", None)
                return _make_cache_key(
                    args,
                    kwargs,
                    use_request=use_request,
                    path=path,
                    query_args=query_args,
                )

            def _make_cache_key_query_string(
                path: str | None = None,
                query_args: _QueryArgs | None = None,
            ) -> str:
                """Create consistent keys for query string arguments.

                Produces the same cache key regardless of argument order, e.g.,
                both `?limit=10&offset=20` and `?offset=20&limit=10` will
                always produce the same exact cache key.

                If func is provided and is callable it will be used to hash
                the function's source code and include it in the cache key.
                This will only be done is source_check is True.
                """

                # Create a tuple of (key, value) pairs, where the key is the
                # argument name and the value is its respective value. Order
                # this tuple by key. Doing this ensures the cache key created
                # is always the same for query string args whose keys/values
                # are the same, regardless of the order in which they are
                # provided.

                if query_args is None:
                    pairs: Iterable[tuple[str, str]] = request.args.items(multi=True)
                else:
                    pairs = query_args_as_pairs(query_args)

                args_as_sorted_tuple = tuple(sorted(pair for pair in pairs))
                # ... now hash the sorted (key, value) tuple so it can be
                # used as a key for cache. Turn them into bytes so that the
                # hash function will accept them
                args_as_bytes = str(args_as_sorted_tuple).encode()
                cache_hash = self._get_hash_method(hash_method)(args_as_bytes)

                # Use the source code if source_check is True and update the
                # cache_hash before generating the hashing and using it in
                # cache_key
                if self._get_source_check(source_check) and callable(f):
                    func_source_code = inspect.getsource(f)
                    cache_hash.update(func_source_code.encode("utf-8"))

                cache_hash = str(cache_hash.hexdigest())

                if callable(key_prefix):
                    cache_key = key_prefix()
                elif "%s" in key_prefix:
                    cache_key = key_prefix % (request.path if path is None else path)
                else:
                    cache_key = key_prefix

                return cache_key + cache_hash

            def _make_cache_key(
                args: tuple[Any, ...],
                kwargs: dict[str, Any],
                use_request: bool,
                path: str | None = None,
                query_args: _QueryArgs | None = None,
            ) -> str:
                if query_string:
                    return _make_cache_key_query_string(path, query_args)
                else:
                    cache_key: str
                    if callable(key_prefix):
                        cache_key = key_prefix()
                    elif "%s" in key_prefix:
                        if path is not None:
                            cache_key = key_prefix % path
                        elif use_request:
                            cache_key = key_prefix % request.path
                        else:
                            # Outside of a request context ``url_for``
                            # defaults to an external URL, which would not
                            # match the key the request stored.
                            cache_key = key_prefix % url_for(
                                f.__name__, _external=False, **kwargs
                            )
                    else:
                        cache_key = key_prefix

                if self._get_source_check(source_check) and callable(f):
                    func_source_code = inspect.getsource(f)
                    func_source_hash = self._get_hash_method(hash_method)(
                        func_source_code.encode("utf-8")
                    )
                    func_source_hash = str(func_source_hash.hexdigest())

                    cache_key += func_source_hash

                return cache_key

            cached_fn = cast("_CachedFunction[P, R]", decorated_function)
            cached_fn.uncached = f
            cached_fn.cache_timeout = timeout
            cached_fn.make_cache_key = default_make_cache_key
            return cached_fn

        return decorator

    def delete_cached(
        self,
        f: _AnyCachedFunction,
        path: str | None = None,
        query_args: _QueryArgs | None = None,
        **kwargs: Any,
    ) -> bool:
        """Delete the cached value of a :meth:`cached` decorated function.

        Example::

            @app.route("/works")
            @cache.cached(query_string=True)
            def view_works():
                return do_search(request.args)

            cache.delete_cached(view_works, "/works", {"limit": 15})

        If you are calling this outside of a request context pass ``path`` and
        when the function was decorated with ``query_string=True`` you also
        have to pass ``query_args``.

        :param f: The decorated function whose cached value to delete.
        :param path: The ``request.path`` the value was cached for.
        :param query_args: The query string the value was cached for, as a
                           query string, a mapping or an iterable of
                           ``(key, value)`` pairs. Only used when the function
                           was decorated with ``query_string=True``.
        :param kwargs: The view arguments, passed to ``url_for()`` to build
                       the path when ``path`` is not given.
        """
        return self.delete(f.make_cache_key(path=path, query_args=query_args, **kwargs))
